#!/bin/bash
if [[ $1 == "install" ]];then


	if [ ! -f /scripts/$2.sh ];then
		echo "Script Not Found!"; 
		exit;
	elif [ $2 == "" ];then
	{
		echo "Install:Installs Package";
	}
	fi
	/scripts/$2.sh
elif [[ $1 == "-h" ]];then
	echo "Reconized Arguments:Install,-h,ibinary,contact";
elif [[ $1 == "ibinary" ]];then
	echo "WIP";
elif [[ $1 == "contact" ]];then
	echo "Made By Zachary James Schlotman. Age 13.";
else

	echo "Usage:		Install:Looks for package."
	echo "			-h:Help";
	echo "			ibinary:WIP";
	echo "			contact:Contact info";
fi
